version: "3.2"
services:
  loaner:
    image: alfredherr/loaner:1.12
    hostname: loaner
    container_name: loaner
    depends_on:
      - "lighthouse"
    command: ["bash","./wait-a-sec.sh"]
    ports:
      - "80:8080"
      - "7777:7777"
    volumes:
      - "/demo:/demo"
  lighthouse:
    image: alfredherr/lighthouse:1.3
    hostname: lighthouse
    container_name: lighthouse
    ports:
      - "81:8181"
      - "4053:4053"
    volumes:
      - "/demo:/demo"
