version: "3.2"
services:
  akka-demo:
    image: alfredherr/loaner:1.2
    container_name: loaner
    ports:
      - "80:8080"
      - "7777:7777"
    volumes:
      - "/Users/alfredherr/Projects/Demo2/Demo/Loaner/demo:/demo"
    extra_hosts:
      - "akkaclient:127.0.0.1"
      - "lighthouse:192.168.1.138"
